// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB460M_3l_FKuDo5JwQZ7-B4p1B8Y8zH1k',
    appId: '1:706725943825:web:2096fd6a31b9df76c52fb0',
    messagingSenderId: '706725943825',
    projectId: 'todo-e0bbc',
    authDomain: 'todo-e0bbc.firebaseapp.com',
    storageBucket: 'todo-e0bbc.appspot.com',
    measurementId: 'G-28CFT73R4X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC649Ct-UdBAVvv0dIMLGBZXj-vk32HZH8',
    appId: '1:706725943825:android:be0f70f298d658e8c52fb0',
    messagingSenderId: '706725943825',
    projectId: 'todo-e0bbc',
    storageBucket: 'todo-e0bbc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6u7Ra5vET26iQwnAW4BuXTRGxZR7VXEY',
    appId: '1:706725943825:ios:3227f4c303608c47c52fb0',
    messagingSenderId: '706725943825',
    projectId: 'todo-e0bbc',
    storageBucket: 'todo-e0bbc.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6u7Ra5vET26iQwnAW4BuXTRGxZR7VXEY',
    appId: '1:706725943825:ios:a972f6418f4159cdc52fb0',
    messagingSenderId: '706725943825',
    projectId: 'todo-e0bbc',
    storageBucket: 'todo-e0bbc.appspot.com',
    iosBundleId: 'com.example.todo.RunnerTests',
  );
}
